version: '3'

services:
  postgres:
    image: postgres:13.4-alpine
    container_name: django_chatbot_postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=chatbot
      - POSTGRES_PASSWORD=chatbot
      - POSTGRES_DB=chatbot
    ports:
      - "5432:5432"

  redis:
    image: redis:6.2-alpine
    container_name: django_chatbot_redis
    ports:
      - "6379:6379"

volumes:
  postgres_data: