"""
Django settings for testproject project.

Generated by 'django-admin startproject' using Django 2.2.

For more information on this file, see
https://docs.djangoproject.com/en/2.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/2.2/ref/settings/
"""

import os
from decouple import config

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/2.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = config('SECRET_KEY')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['*']

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django_chatbot',
    'testproject',
    'testapp',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'testproject.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'testproject.wsgi.application'

# Database
# https://docs.djangoproject.com/en/2.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': config('DB_NAME', default='chatbot'),
        'USER': config('DB_USER', default='chatbot'),
        'PASSWORD': config('DB_PASSWORD', default='chatbot'),
        'HOST': config('DB_HOST', default='localhost'),
        'PORT': config('DB_PORT', default=5432, cast=int),
    }
}


# Password validation
# https://docs.djangoproject.com/en/2.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator', # noqa
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator', # noqa
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator', # noqa
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',# noqa
    },
]

# Internationalization
# https://docs.djangoproject.com/en/2.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# django-chatbot

DJANGO_CHATBOT = {
    'BROKER': config("CHATBOT_BROKER", default="redis://localhost:6379/0"),
    'WEBHOOK_DOMAIN': config(
        'CHATBOT_WEBHOOK_DOMAIN', default='https//xxx.ngrok.io'
    ),
    'BOTS': [
        {
            'NAME': config('NOTES_BOT_NAME', default='@BotnameBot'),
            'TOKEN': config('NOTES_BOT_TOKEN', default='xxxx:bot-token'),
            'ROOT_HANDLERCONF': "testapp.notes.handlers"
        },
        {
            'NAME': config('DUMMY_BOT_NAME', default='@BotnameBot'),
            'TOKEN': config('DUMMY_BOT_TOKEN', default='xxxx:bot-token'),
            'ROOT_HANDLERCONF': "testapp.dummy.handlers"
        },
    ]
}

# Logging
USE_PAPERTRAIL = config("USE_PAPERTRAIL", default=False, cast=bool)

if USE_PAPERTRAIL:
    PAPERTRAIL_ADDRESS = config("PAPERTRAIL_ADDRESS")
    PAPERTRAIL_PORT = config("PAPERTRAIL_PORT", cast=int)
    LOGGING = {
        'version': 1,
        'disable_existing_loggers': False,
        'formatters': {
            'verbose': {
                'format': '{asctime} [{levelname}] [{filename}:{lineno} - {funcName}() ] {name}: {message}',  # noqa
                'style': '{',
            },
            'simple': {
                'format': '{levelname} {message}',
                'style': '{',
            },
        },
        'handlers': {
            'SysLog': {
                'level': 'DEBUG',
                'class': 'logging.handlers.SysLogHandler',
                'formatter': 'verbose',
                'address': (PAPERTRAIL_ADDRESS, PAPERTRAIL_PORT)
            },
        },
        'loggers': {
            'testapp': {
                'handlers': ['SysLog'],
                'level': 'DEBUG',
                'propagate': True,
            },
            'django_chatbot': {
                'handlers': ['SysLog'],
                'level': 'DEBUG',
                'propagate': True,
            },
        },
    }

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/2.2/howto/static-files/

STATIC_URL = '/static/'
